project_name: "dense_mesh"
output_folder_base: "./generate_res/"
data:
  eval_dataset_path: "./demo_data/demo"
  num_workers: 10

data_processing:
  overfit: false 
  dec_to_facenum: 5000
  y_up: true
  n_discrete_size: 256
  vertex_order: "zyx"
  max_len: 20000
  min_len: 500
  pc_num: 16384
  total_pc_num: 40960
  windowing:
    window_size: 1000
    window_stride: 500
    split_method: "sliding_window"
  val_augmentation:
    shift_augment: false
    scale_augment: false
    dec_augment: false
    rot_augment: false
    sample_augment: false

model:
  model_path: "./ckpt/meshRipple_nsa.pth"
  # model_path: "./ckpt/meshRipple_10k.pth"
  model_version: "v1-nsa"
  # model_version: "full_attn"
  feature_dim: 1024
  num_heads: 16
  root_pred_depth: 3
  context_embedding_dim: 256
  num_classify: 100
  hourglass_depth: [4, 4, 9] # [4, 4, 3*3]
  input_embe_pos: "no"
  conditioned_on_pc: true
  encoder_freeze: false

accelerator:
  mixed_precision: "bf16" # "no", "fp16", "bf16"

generate:
  batch_size: 4
  top_k: 50
  top_p: 0.95
  temperature: 0.9
  eos_aug: true
  wr_fix: true